### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by jberkhahn** [emirozer/cf-doctor-plugin#3]
Hello,

It looks like there's a version mismatch between your plugin and the version advertised on plugins.cloudfoundry.org and in the CLI. Your plugin is advertised as v1.0.1, but the version installed is only 1.0.0

Not sure if this is unintentional or there really is a v1.0.1 around somewhere.

Thanks!

**Comment by emirozer** [comment]
Hi,

Thank you for reporting i realised i didnt updated it

https://github.com/emirozer/cf-doctor-plugin/blob/master/main.go#L268

So its actually 1.0.1 but i forgot to update it in the code..
