### ISSUE TITLE
Host: routes <--->  Domain: found when running in empty space

### ISSUE THREAD

**Issue by bkrannich** [emirozer/cf-doctor-plugin#6]
I'm getting the following message if I run `cf doctor` in a space that doesn't contain any apps:

```
Following routes do not have any app bound to them:
Host: routes <--->  Domain: found
```

I'm guessing this is the parsed output of `cf routes` in an empty space:

```
Getting routes for org <...> / space <...> as <...> ...

space   host   domain   port   path   type   apps   service
No routes found
```

**Comment by emirozer** [comment]
Thanks for the report, I am going to check it and report back.

**Comment by emirozer** [comment]
Yes I am able to reproduce the problem. Will provide a fix soon.
